Домашняя работа (Ахметзанов Марат)
MaratAkhmetzanov/js-part-0 pull request #1
Opened 2022-12-08 18:56 UTC by MaratAkhmetzanov

1. Yarn поставил.
2. Форк: https://github.com/MaratAkhmetzanov/js-part-0.
3. Репозиторий склонирован и создана ветка homework.
4, 5. ESLint уже стоял. Отключил линтер для двух строк, чтобы не отключать правила.
6. Дописал функцию areEqual(), чтобы она работала с массивами. Сделал через stringify, но не уверен, что это корректно.
7. Запускал код через node.
8. Дописал функции, чтобы все тесты проходили. Также добавил несколько тестов, которых не хватало, на мой взгляд.
9. Кроме ошибок no-array-constructor и no-new-object, ошибок не было (если линтер правильно всё проверил).

2022-12-09 18:07 UTC, ipetropolsky requested changes

2022-12-09 18:07 UTC, ipetropolsky commented on index.js
> +        return a.length === b.length ? JSON.stringify(a) === JSON.stringify(b) : false;
Да, `stringify` не всегда выдаёт очевидный результат.
```js
areEqual([{}], [new Set([1,2])]) // true
areEqual([null], [NaN]) // true
```
Поскольку в задании было только про массивы примитивов, можно и так оставить. Вообще лучше просто перебрать элементы и сравнить каждый с каждым.

2022-12-09 18:07 UTC, ipetropolsky commented on index.js
> +const getTypesOfItems = (arr) => arr.map((element) => getType(element));
Можно даже так для краткости:
```suggestion
const getTypesOfItems = (arr) => arr.map(getType);
```
Но у тебя безопаснее, т.к. в `getType` не приедут доп. аргументы, которые передаёт `map`.

2022-12-09 18:07 UTC, ipetropolsky commented on index.js
> +            if (getType(arr[index]) !== getType(arr[0])) {
Норм, но `getType` вызывается в два раза больше, чем у массива элементов.
А ещё глянь на методы массивов: `some`, `every`.

2022-12-09 18:07 UTC, ipetropolsky commented on index.js
> +    if (arr.length && arr.length > 1) {
👍

2022-12-09 18:07 UTC, ipetropolsky commented on index.js
> +    if (getType(value) === 'number') {
Я бы тут не завязывался на `getType`, вдруг у него какая-то своя логика внутри. Нам тут нужен честный тип.

2022-12-09 18:07 UTC, ipetropolsky commented on index.js
> +    return Object.prototype.toString.call(value).split(' ')[1].slice(0, -1).toLowerCase();
Интересная находка. Но с `async () => 123` и другими типами из двух слов будет не очень красивый результат.

2022-12-09 18:07 UTC, ipetropolsky commented on index.js
> +    return itemsType.length === collection.size;
👍

2022-12-09 18:07 UTC, ipetropolsky commented on index.js
> +            result[getRealType(element)] = 0;
`result` же массив. Если хочешь так использовать, нужен объект. Это работает, потому что ты можешь проставить произвольные поля и инстансу массива в том числе, но так не очень хорошо делать. Непонятно просто.

2022-12-09 18:07 UTC, ipetropolsky commented on index.js
> +        // eslint-disable-next-line no-new-object
👍

2022-12-09 18:07 UTC, ipetropolsky commented on index.js
> +    undefined,
Может ещё парочку типов найдёшь? )

2022-12-09 18:07 UTC, ipetropolsky commented on index.js
> +test('Date primitive', getType(new Date()), 'object');
https://developer.mozilla.org/en-US/docs/Glossary/Primitive

2022-12-12 11:25 UTC, MaratAkhmetzanov commented on index.js
> +        return a.length === b.length ? JSON.stringify(a) === JSON.stringify(b) : false;
Заменил на проверку через every.

2022-12-12 11:50 UTC, MaratAkhmetzanov commented on index.js
> +const getTypesOfItems = (arr) => arr.map((element) => getType(element));
Не знал, что можно так коротко записывать. Так как безопаснее, оставил свой вариант.

2022-12-12 11:56 UTC, MaratAkhmetzanov commented on index.js
> +            if (getType(arr[index]) !== getType(arr[0])) {
Не понял, что значит «getType вызывается в два раза больше»? Поменял на:
`const firstType = getType(arr[0]);`
`return arr.every((element) => getType(element) === firstType);`

2022-12-12 11:57 UTC, MaratAkhmetzanov commented on index.js
> +    if (getType(value) === 'number') {
Убрал.

2022-12-12 11:58 UTC, MaratAkhmetzanov commented on index.js
> +            result[getRealType(element)] = 0;
Я правильно понял, что нужно заменить `const result = [];` на `const result = {};`?

2022-12-12 12:01 UTC, MaratAkhmetzanov commented on index.js
> +    undefined,
Добавил ещё 9 типов.

2022-12-12 12:04 UTC, MaratAkhmetzanov commented on index.js
> +test('Date primitive', getType(new Date()), 'object');
Я так понял к примитивам относится только определенный список типов?
Поменял текст у тестов.

2022-12-12 12:14 UTC, MaratAkhmetzanov commented on index.js
> +    return Object.prototype.toString.call(value).split(' ')[1].slice(0, -1).toLowerCase();
Вот этот момент не понял. 
1. Как должны выглядеть реальные типы? 
2. Я сначала через свитч сделал, но решил, что слишком страшная конструкция получится. Если же делать через instance of, то там ещё страшнее код становится. Есть ли какой-то простой способ получение реального типа без большого ветвления?

2022-12-12 12:23 UTC, ipetropolsky commented on index.js
> +    return Object.prototype.toString.call(value).split(' ')[1].slice(0, -1).toLowerCase();
1) Как тебе нравится, я просто обращаю внимание, что бывают «типы» из двух слов, и lowercase их не очень красиво обработает.
2) Нет )

2022-12-12 12:24 UTC, ipetropolsky commented on index.js
> +            result[getRealType(element)] = 0;
Да. У массива пользуемся только встроенными свойствами и методами + получение по индексу. В объект можем добавлять свои ключи.

2022-12-12 12:27 UTC, ipetropolsky commented on index.js
> +            if (getType(arr[index]) !== getType(arr[0])) {
Он вызывался на каждый элемент плюс ещё каждый раз для первого элемента.

2022-12-12 12:28 UTC, ipetropolsky approved these changes

2022-12-21 22:15 UTC, merged